### ทดสอบดูข้อมูลหมวดหมู่ทั้งหมด
GET http://localhost:3000/categories


### สมัครสมาชิกคนที่ 1
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "name": "สมชาย ใจดี",
  "email": "somchai@example.com",
  "password": "123456",
  "phone": "081-234-5678",
  "age": 28
}


### สมัครสมาชิกคนที่ 2
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "name": "สมหญิง รักดี",
  "email": "somying@example.com",
  "password": "abcdef",
  "phone": "082-345-6789",
  "age": 25,
  "avatar": "https://via.placeholder.com/150"
}


### ดูสมาชิกทั้งหมด
GET http://localhost:3000/user


### ดูสมาชิกตาม ID
GET http://localhost:3000/user/1


### ทดสอบเข้าสู่ระบบ (สำเร็จ)
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "somchai@example.com",
  "password": "123456"
}


### ทดสอบเข้าสู่ระบบ (รหัสผิด)
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "somchai@example.com",
  "password": "wrongpassword"
}


### ทดสอบเปลี่ยนรหัสผ่าน
PUT http://localhost:3000/user/password
Content-Type: application/json

{
  "email": "somchai@example.com",
  "oldPassword": "newpass123",
  "newPassword": "newpass1234"
}


### ทดสอบ login ด้วยรหัสใหม่
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "somchai@example.com",
  "password": "newpass1234"
}